### ISSUE TITLE
qbschema not working with play-json 2.4.x

### ISSUE THREAD

**Issue by dpanelli** [qb-project/qbproject#53]
Hello ,
 upgrading my play application form 2.3.9 to 2.4.2 gives me those exceptions on  QBValidator.validate

An exception or error caused a run to abort: play.api.libs.json.JsObject.$bslash(Ljava/lang/String;)Lplay/api/libs/json/JsValue; 
java.lang.NoSuchMethodError: play.api.libs.json.JsObject.$bslash(Ljava/lang/String;)Lplay/api/libs/json/JsValue;
	at org.qbproject.schema.package$JsObjectExtensions.get(package.scala:32)

Are you working on porting it to play 2.4?

**Comment by edgarmueller** [comment]
Hi,
no, we didn't yet undertake porting qb to play to 2.4, since we are currently only using it in a play 2.3 environment. But I'll try a have look at it and come back to you.

**Comment by edgarmueller** [comment]
Hi, 
I've ported qbschema to Play 2.4 and Scala 2.11. The current version number hence has been updated to 0.4.2 in case you wanna update. I also removed all other modules like qbcsv and qbplay since I didn't have the time to port them. Let me know whether this works for you and if you need anything else.

**Comment by dpanelli** [comment]
Thank you , I will test as soon as possible:)

On 14 July 2015 at 14:33, edgarmueller <notifications@github.com> wrote:

> Hi,
> I've ported qbschema to Play 2.4 and Scala 2.11. The current version
> number hence has been updated to 0.4.2 in case you wanna update. I also
> removed all other modules like qbcsv and qbplay since I didn't have the
> time to port them. Let me know whether this works for you and if you need
> anything else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qb-project/qbproject/issues/53#issuecomment-121225628>
> .
>



-- 

*Davide Panelli*

Solutions Architect

*Byte-Code srl*

*mobile*: +39 347 87 505 88

office: +39 02 9840047

www.byte-code.com
